### ISSUE TITLE
Comment-out lines

### ISSUE THREAD

**Issue by iveel36** [googleinterns/spacetime-sim-2020#20]
https://github.com/googleinterns/spacetime-sim-2020/blob/5b646eb3c8f8ae2bd2643c5c7df2516d57214c8f/Gilbert_code/benchmarks/grid_simulation_non_rl.py#L94

If they are useful, explain when they should be uncommented out and be used. Otherwise, remove them.

**Comment by gilbert-bahati** [comment]
link to FLOW tutorials
