### ISSUE TITLE
What is the difference between PO_ENV vs ENV? Comment it somewhere or use a complete word for "PO".

### ISSUE THREAD

**Issue by iveel36** [googleinterns/spacetime-sim-2020#23]
https://github.com/googleinterns/spacetime-sim-2020/blob/5b646eb3c8f8ae2bd2643c5c7df2516d57214c8f/Gilbert_code/centralized/centralized_env.py#L32

**Comment by gilbert-bahati** [comment]
name and link default params thesis vs presslight
