### ISSUE TITLE
Function document: rl_actions is not int

### ISSUE THREAD

**Issue by lccycc-google** [googleinterns/spacetime-sim-2020#31]
https://github.com/googleinterns/spacetime-sim-2020/blob/05306dd549cb5c52af7dcb8ce85b2914b99496c4/Gilbert_code/centralized/centralized_env.py#L252

it shall be a list of int?

I thought that it is a list of int, the length equals to the number of traffic lights in network

**Comment by gilbert-bahati** [comment]
For centralized_env, its a single int. Not a list

The int is mapped to the correct actions in,
line 277 : actions = self.action_dict[rl_actions] 

ie.  self.action_dict =  {rl_action: (action_for each_traffic_light)}
{1: (0,0,0), 2: (0,1,0) ........etc)}
